services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env.docker
    volumes:
      - backend_uploads:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  web:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - api

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    depends_on:
      - mongo

volumes:
  mongo_data:
  backend_uploads:
