from typing import Protocol, Optional, List
from ..domain.models import Invite, Video


class InviteRepoPort(Protocol):
    def create(self, invite: Invite) -> Invite: ...
    def get_by_token(self, token: str) -> Optional[Invite]: ...
    def list_all(self) -> List[Invite]: ...
    def update(self, invite: Invite) -> None: ...


class VideoRepoPort(Protocol):
    def create(self, video: Video) -> Video: ...
    def get(self, vid: str) -> Optional[Video]: ...
    def list_by_invite(self, invite_id: str) -> List[Video]: ...
    def update(self, video: Video) -> None: ...